name = "story_bakery/blender_to_roblox_animation"
version = "0.1.0"
license = "MIT"

[target]
environment = "luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }
setup-project-configs = { repo = "https://github.com/StoryBakery/setup-project-configs", rev = "8e77c9722c25b0a4ea6ed1415ab18fc8db2ff9e2" }
pesde-gitrev = { repo = "https://github.com/StoryBakery/pesde-gitrev", rev = "a2d6f1e71ac6264ff2b48fd2178271f80135772e" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
TypeInfos = { repo = "https://github.com/StoryBakery/TypeInfos", rev = "a7362072a5afd85bee6583f05398a09438a039b5" }
LinearInterpolation = { repo = "https://github.com/StoryBakery/LinearInterpolation", rev = "c522819b5515edb45f1518244252f58c8f9e05ee" }
MathUtil = { repo = "https://github.com/StoryBakery/MathUtil", rev = "f4889bc7b605e4f4bc1acb53997bb48dcb15114d" }
BezierCurve = { repo = "https://github.com/StoryBakery/BezierCurve", rev = "bc69222f5c6bd59337815c94446eabe07c02515a" }
BezierInterpolator = { repo = "https://github.com/StoryBakery/BezierInterpolator", rev = "71b5773558c918d0ee15d000bbcf95ac6505f433" }
ValueByPriority = { repo = "https://github.com/StoryBakery/ValueByPriority", rev = "f4ca970605f7bbce20fb12e9ae1d0e2226c3a553" }

